### ISSUE TITLE
How do I deploy the project to Heroku?

### ISSUE THREAD

**Issue by Grogs** [HcomCoolCode/CoolCodeBot#1]
To test/verify changes, I've created my own facebook app/page, and want to deploy my own instance of the app to Heroku.

I've checked out master and created my own Heroku instance. When I try to push master to Heroku, it fails:

```
remote:  !     Push rejected, no Cedar-supported app detected
remote: HINT: This occurs when Heroku cannot detect the buildpack
remote:       to use for this application automatically.
remote: See https://devcenter.heroku.com/articles/buildpacks
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to boiling-cove-93944.
remote:
To https://git.heroku.com/boiling-cove-93944.git
```

What am I missing? I couldn't find any hints in the Travis YAML.

**Comment by matyjas** [comment]
think we worked through this :)

**Comment by Grogs** [comment]
I had to set the build pack for my Heroku instance before pushing, by running:

`heroku buildpacks:set https://github.com/HashNuke/heroku-buildpack-elixir`

I also had to set an environment variable for my Facebook Page Access Token, with:

`heroku config:set FB_PAGE_ACCESS_TOKEN="my_super_secret_token"`
